arch?

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -10,14 +10,32 @@ source "${plugin_dir}/lib/utils.bash"
 
 mkdir -p "$ASDF_DOWNLOAD_PATH"
 
-# TODO: Adapt this to proper extension and adapt extracting strategy.
-release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
+case "$(uname -sm)" in
+	"Linux i686") ext="Linux_32bit.tar.gz" ;;
+	"Linux x86_64") ext="Linux_64bit.tar.gz" ;;
+	"Linux armv6l") ext="Linux_ARMv6.tar.gz" ;;
+	"Linux armv7l") ext="Linux_ARMv7.tar.gz" ;;
+	"Linux aarch64") ext="Linux_ARM64.tar.gz" ;;
+	"Darwin x86_64") ext="macOS_64bit.tar.gz" ;;
+	"Darwin arm64") ext="macOS_ARM64.tar.gz" ;;
+	"MINGW32_NT-6.2 i686") ext="Windows_32bit.zip" ;;
+	"MINGW64_NT-6.2 x86_64") ext="Windows_64bit.zip" ;;
+	"WSL2 i686") ext="Windows_32bit.zip" ;;
+	"WSL2 x86_64") ext="Windows_64bit.zip" ;;
+	*) fail "asdf-$TOOL_NAME does not support arch '$(uname -sm)'." ;;
+esac
+
+release_file="$ASDF_DOWNLOAD_PATH/${TOOL_NAME}_${ASDF_INSTALL_VERSION}_${ext}"
 
 # Download tar.gz file to the download directory
 download_release "$ASDF_INSTALL_VERSION" "$release_file"
 
-#  Extract contents of tar.gz file into the download directory
-tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+# Extract contents of release file into the download directory
+case "$release_file" in
+	*.zip) unzip -d "$ASDF_DOWNLOAD_PATH" "$release_file" || fail "Could not extract $release_file" ;;
+	*.tar.gz) tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file" ;;
+	*) fail "Unknown file extension for $release_file" ;;
+esac
 
-# Remove the tar.gz file since we don't need to keep it
+# Remove the release file since we don't need to keep it
 rm "$release_file"
