simplify?

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -8,4 +8,19 @@ plugin_dir=$(dirname "$(dirname "$current_script_path")")
 # shellcheck source=./lib/utils.bash
 source "${plugin_dir}/lib/utils.bash"
 
-install_version "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
+if [ "$ASDF_INSTALL_TYPE" != "version" ]; then
+	fail "asdf-$TOOL_NAME supports release installs only"
+fi
+
+bin_path="${ASDF_INSTALL_PATH%/bin}/bin/"
+
+(
+	mkdir -p "${bin_path}"
+	cp -r "$ASDF_DOWNLOAD_PATH"/* "$bin_path"
+	text -x "$bin_path/$TOOL_NAME" ||
+		test -f "$bin_path/${TOOL_NAME}.exe" ||
+		fail "No $bin_path/$TOOL_NAME executable found"
+) || (
+	rm -rf "$bin_path" &&
+	fail "An error occurred while installing $TOOL_NAME $ASDF_INSTALL_VERSION"
+)
